export const frEditor = {
  toolbar: "Mise en forme",
  bold: "Gras",
  italic: "Italique",
  strike: "Barré",
  code: "Code en ligne",
  codeBlock: "Bloc de code",
  noLanguage: "Sans langue",
  heading: "Titre",
  headingLevel: (n: number) => `Titre ${n}`,
  paragraph: "Paragraphe",
  bullet: "Liste",
  ordered: "Liste numérotée",
  task: "Case à cocher",
  quote: "Citation",
  link: "Lien",
  table: "Tableau",
  image: "Image",
  imageAlt: "description",
  imagePath: "assets/nom.png",
  bubble: "Mise en forme de la sélection",
  placeholder: "texte",
  column: (n: number) => `Colonne ${n}`,
  languages: [
    "ts",
    "tsx",
    "js",
    "json",
    "bash",
    "md",
    "css",
    "html",
    "sql",
    "python",
    "rust",
    "go",
    "yaml",
  ] as const,
};
