const s = (n: number) => (n > 1 ? "s" : "");

export const fr = {
  search: "Rechercher une note…",
  obsidian: "Obsidian",
  newNote: "Nouvelle note",
  untitled: "Sans titre",
  today: "aujourd'hui",
  yesterday: "hier",
  links: (n: number) => `${n} lien${s(n)}`,
  saved: "Enregistré",
  local: "local",
  unsaved: "Non enregistré",
  saving: "Enregistrement…",
  edit: "Modifier",
  preview: "Aperçu",
  editor: "Contenu de la note",
  linkedTickets: "Tickets liés",
  backlinks: "Rétroliens",
  mentionsOnce: "mentionne cette note",
  mentions: (n: number) => `${n} mentions`,
  conflict: "Modifié hors de Kibo",
  reload: "Recharger",
  keepMine: "Garder ma version",
  emptyList: "Aucune note dans ce dossier.",
  noResult: "Aucune note ne correspond.",
  pick: "Choisis une note ou crées-en une.",
  emptyWidget: "Aucune note pour l'instant.",
  loadFailed: "Impossible de lire les notes.",
  saveFailed: "Impossible d'enregistrer la note.",
  createFailed: "Impossible de créer la note.",
};
