export const fr = {
  filter: { label: "Tickets affichés", mineAndAgents: "Moi + agents", all: "Tous" },
  counter: (shown: number, total: number, filter: string) => `${shown} / ${total} · ${filter}`,
  labelFilter: {
    label: "Filtrer par étiquette",
    all: "Étiquette : toutes",
    one: (label: string) => `Étiquette : ${label}`,
    failed: "Impossible de lire ou d'enregistrer le filtre d'étiquette.",
  },
  hidden: (n: number) => `${n} masqué${n > 1 ? "s" : ""} · Tout afficher`,
  newTicketIn: (status: string) => `Nouveau ticket dans ${status}`,
  actions: (key: string) => `Actions ${key}`,
  moveTo: "Déplacer vers",
  open: "Ouvrir",
  remove: "Supprimer…",
  removeTitle: (key: string) => `Supprimer ${key} ?`,
  removeHelp: (children: number) =>
    children === 0
      ? "Ses liens seront supprimés aussi. Cette action est irréversible."
      : `Ses ${children} sous-ticket${children > 1 ? "s" : ""} et ses liens seront supprimés aussi. Cette action est irréversible.`,
  removeConfirm: "Supprimer",
  cancel: "Annuler",
  orderUnavailable: "Impossible de lire l'ordre des cartes.",
  drag: {
    help: "Pour déplacer une carte, appuie sur Espace ou Entrée, choisis sa place avec les flèches, puis appuie de nouveau sur Espace ou Entrée. Échap annule.",
    picked: (key: string) => `${key} saisi.`,
    over: (key: string, target: string) => `${key} au-dessus de ${target}.`,
    outside: (key: string) => `${key} hors des colonnes.`,
    dropped: (key: string, target: string) => `${key} déposé sur ${target}.`,
    cancelled: (key: string) => `Déplacement de ${key} annulé.`,
  },
  moveFailed: (key: string) => `Impossible de déplacer ${key}.`,
  waitingOn: (key: string) => `attend ${key}`,
  blockedReason: (reason: string) => `Motif : ${reason}`,
  ci: { ok: "CI réussie", error: "CI cassée", running: "CI en cours", neutral: "CI sans verdict" },
  ciUnavailable: (message: string) => `CI indisponible : ${message}`,
  run: {
    queued: (position: number | null) => (position === null ? "En file" : `En file #${position}`),
    waiting: "Attend",
    failed: "Échec",
  },
  block: {
    title: (key: string) => `Bloquer ${key}`,
    description: "Un ticket bloqué attend une condition extérieure au projet.",
    reason: "Motif",
    placeholder: "Informations attendues du client",
    cancel: "Annuler",
    confirm: "Bloquer",
  },
};
