const plural = (n: number, one: string, many: string) => (n > 1 ? many : one);

export const fr = {
  title: "Questions",
  widgetTitle: (n: number) => `Questions ouvertes · ${n}`,
  provisional: (value: string) => `provisoire : ${value}`,
  options: "Options",
  confirm: "Valider le choix provisoire",
  other: "Autre réponse…",
  reply: "Répondre",
  answerTo: (title: string) => `Répondre à ${title}`,
  answeredBy: (who: string, when: string) => `Répondu par ${who} · ${when}`,
  answer: (value: string) => `Réponse : ${value}`,
  deliveredTo: (label: string) => `transmise à ${label}`,
  toDeliver: "à transmettre",
  deliver: (n: number) => `Transmettre à l'agent (${n})`,
  deliverFor: (key: string, n: number) => `Transmettre à l'agent (${n}) · ${key}`,
  delivered: (label: string) => `Transmis à ${label}`,
  nothingToDeliver: "Aucune réponse à transmettre.",
  noSession: "Aucune session à reprendre : assigne le ticket, le brief portera les réponses.",
  deliverFailed: "Impossible de transmettre les réponses.",
  answerFailed: "Impossible d'enregistrer la réponse.",
  removeFailed: "Impossible de supprimer la question.",
  loadFailed: "Impossible de lire les questions.",
  newQuestion: "Nouvelle question",
  openView: "Ouvrir les questions →",
  emptyOpen: "Aucune question ouverte.",
  empty: "Aucune question.",
  readOnly: "Lecture seule",
  remove: "Supprimer",
  removeTitle: (title: string) => `Supprimer « ${title} » ?`,
  removeHelp: "La question et sa réponse disparaissent pour tout le projet.",
  cancel: "Annuler",
  agent: "agent",
  imported: (ref: string) => `import ${ref}`,
  openTicket: (key: string, title: string) => `${key} · ${title}`,
  questions: (n: number) => `${n} ${plural(n, "question", "questions")}`,
  scope: { label: "État", open: "Ouvertes", answered: "Répondues", all: "Toutes" },
  ticketFilter: {
    label: "Ticket",
    all: "Tous les tickets",
    search: "Rechercher une clé",
    none: "Aucun ticket",
  },
  age: {
    now: "à l'instant",
    minutes: (n: number) => `il y a ${n} min`,
    hours: (n: number) => `il y a ${n} h`,
    days: (n: number) => `il y a ${n} j`,
  },
  dialog: {
    title: "Nouvelle question",
    description: "Une question à valider sur un ticket, visible de tout le projet.",
    ticket: "Ticket",
    pickTicket: "Choisir un ticket",
    questionTitle: "Question",
    context: "Contexte (Markdown)",
    options: "Options, une par ligne",
    optionsHelp: "6 options au plus.",
    tooMany: "6 options au plus.",
    duplicate: "Deux options identiques.",
    provisional: "Choix provisoire",
    none: "Aucun",
    cancel: "Annuler",
    create: "Créer la question",
    failed: "Impossible de créer la question.",
  },
};
